spring.profiles.active = jen

# url property specific to environment
spring.datasource.username= postgres
spring.datasource.password= admin

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

# App Properties
app.jwtSecret= baibasSecretKey
app.jwtExpirationMs= 86400000

# MVC
spring.mvc.view.prefix = /WEB-INF/jsp/
spring.mvc.view.suffix = .jsp

# Logging
logging.level.org.springframework.web = DEBUG
logging.level.org.hibernate.SQL = INFO

server.port=8082
